### PR TITLE
Upgrade to Ansible 2.1

### LINKED ISSUE #29: Autocomplete not working with dynamic inventories
I'm using dynamic inventories generated from EC2 and Consul.
And the autocomplete for `cloud ssh` is not working.

### PR DESCRIPTION
**Pull request by MiLk**
Todo:
- [x] Bump ansible version
- [x] Update the `cloud ssh` command
- [ ] Update the [human_log](https://github.com/AerisCloud/AerisCloud/blob/develop/ansible/plugins/callbacks/human_log.py) callback plugin
- [ ] Update the [history](https://github.com/AerisCloud/AerisCloud/blob/develop/ansible/plugins/callbacks/history.py) callback plugin
- [x] Update the [aeriscloud_service](https://github.com/AerisCloud/AerisCloud/blob/develop/ansible/plugins/actions/aeriscloud_service.py) action plugin
- [x] Update the [ansible](https://github.com/AerisCloud/AerisCloud/blob/develop/aeriscloud/ansible.py) module
  - `Ansible 2.0 has deprecated the “ssh” from ansible_ssh_user, ansible_ssh_host, and ansible_ssh_port to become ansible_user, ansible_host, and ansible_port.`
- [x] Replace [ansible shell](https://github.com/dominis/ansible-shell) with [ansible console](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/console.py).
- [x] Update [ansible-lint](https://github.com/willthames/ansible-lint)
- [ ] Test
  - [ ] aeris
    - [ ] job
    - [ ] provision
    - [ ] up
  - [ ] cloud
    - [ ] job
    - [x] provision
    - [x] rsync
    - [x] run
    - [x] shell
    - [x] ssh
- [x] fixes #29

### CODE REVIEW

**Comment by christopherobin** [comment]
We should switch the python linter to allow lines up to 120 characters

**Comment by MiLk** [comment]
@tokyowizard @christopherobin I've updated the most critical parts. You should be able to use this branch without any particular issue.
I let you test `aeris` and `cloud job`.

I plan to drop the `human_log` plugin written by @stelcheck as most of the messages are oriented towards Wizcorp developers and some links are invalid.

If you want to keep it, it should be possible to allow external plugins stored in the organization.

I will need to spend time on the history plugin and update ansible-lint.

**Comment by tokyowizard** [comment]
Thank you, @MiLk ! I will try testing this later this week.

**Comment by MiLk** [comment]
The `human_log` and `history` callback plugins have been removed.
`aeris history` will still be present to display the old data.

I'm aiming at a release this week end or next week with the support for Ansible 2.1.
In January, I will start to work on Ansible 2.2 support.

FYI @tokyowizard @christopherobin @stelcheck

**Pull request merged**
