### PR TITLE
Update to Ansible 2.2

### PR DESCRIPTION
**Pull request by MiLk**

### CODE REVIEW

**Review by christopherobin — COMMENTED** [review]
Should we wait for the current CVE to be fixed and upgrade to that instead?

**Comment by MiLk** [comment]
If a proper 2.1.4 version of ansible is released on PyPI we will upgrade to that.

I'm still testing Ansible 2.2, but I didn't have any issues with `cloud provision` and `cloud ssh`, so I guess the API didn't change much.

I would like to have ansible 2.2.1 in that PR to address the CVE.

**Comment by MiLk** [comment]
Blocked by https://github.com/ansible/ansible/issues/20332

**Comment by MiLk** [comment]
The discussion has been moved here https://github.com/ansible/ansible/issues/20886

**Pull request merged**
